### ISSUE TITLE
Update Bug 3.0.10 CTD on startup.

### ISSUE THREAD

**Issue by sjones321** [SkyNetAB/enhanced-portals#179]
http://pastebin.com/FVMZEGEE

had that crash when updating to 3.0.10 from 3.0.9. went back to 3.0.9 no problems. Also to note when installing 3.0.10 with multimc the version info in multimc was still showing it as 3.0.9 double and triple checked I had the right download from your site still same problem. Fine with chilling on 3.0.9 at the moment but I hope this helps you guys.

**Comment by kzarius** [comment]
could you repost the crashlog, it takes me to a blank page. What mc & forge version are you running?

**Comment by sjones321** [comment]
http://pastebin.com/c5Ry2Dbv lets see if this one works. The more I look at that the more I get confused. I am not good at reading them but the text doesn't seem related to ep. but thats all I updated  and when I reverted no problems.

**Comment by sjones321** [comment]
oh on a side note and probably a separate issue you might consider changing your update notifier from ep has an update to enhanced portals has an update as with a lot of mods ep can be confusing.

**Comment by kzarius** [comment]
The crash report points to Thaumic Tinkerer erroring. Can you recheck that it's not TT? It looks like it's requesting an older buildcraft API file. If you update TT, this should fix itself I believe.

**Comment by sjones321** [comment]
I can when I get home from work check that out with Tt. Like I said only happened when updating ep but happy to check

**Comment by sjones321** [comment]
Well sorry for the delay, after much futzing with thaumcraft stuff, I got all of that updated and installed the new ep and it is not crashing to desktop any more. that said you still might want to update the mod info for clients like multimc as its still stating that it is version 3.0.9

**Comment by kzarius** [comment]
will do
